amqp:
    connection_attempts: 40
    hostname: localhost
    port: 5672
    api_port: 15672
    prefetch_count: 10
    retry_delay: 30
    socket_timeout: 30
    vhost: /
    heartbeat_interval: 600


orchestrator:
    create_token_exchange: ptero
    create_token_routing_key: petri.place.create_token
    create_token_queue: petri_create_token

    notify_place_exchange: ptero
    notify_place_routing_key: petri.place.notify
    notify_place_queue: petri_notify_place

    notify_transition_exchange: ptero
    notify_transition_routing_key: petri.transition.notify
    notify_transition_queue: petri_notify_transition


redis:
    host: localhost
    port: 6379


logging:
    version: 1
    disable_existing_loggers: true

    root:
        level: DEBUG
        handlers: [console]

    loggers:
        pika:
            level: INFO
        ptero_petri:
            level: DEBUG
        ptero_petri.implementation.util.signal_handlers:
            level: DEBUG
        'ptero_petri.implementation.brokers':
            level: INFO

    handlers:
        console:
            class: logging.StreamHandler
